import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  ArrowRightLeft,
  BarChart3,
  BadgeCheck,
  Barcode,
  Boxes,
  Building2,
  CalendarDays,
  Calculator,
  ChartNoAxesCombined,
  CheckCircle2,
  CircleHelp,
  ClipboardList,
  Coins,
  CreditCard,
  Download,
  FileBarChart,
  FileCheck2,
  FileText,
  FolderTree,
  HeartHandshake,
  History,
  Landmark,
  MapPin,
  Megaphone,
  Network,
  Package,
  Percent,
  Pill,
  ReceiptText,
  Ruler,
  Scale,
  ShieldCheck,
  ShoppingBasket,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Store,
  Tags,
  Thermometer,
  TrendingUp,
  Truck,
  UserRoundCog,
  UsersRound,
  WalletCards,
  Warehouse,
  WifiOff,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "arrow-left-right": ArrowLeftRight,
  "arrow-right-left": ArrowRightLeft,
  "bar-chart-3": BarChart3,
  "badge-check": BadgeCheck,
  barcode: Barcode,
  boxes: Boxes,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  calculator: Calculator,
  "cash-register": Store,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "check-circle-2": CheckCircle2,
  "circle-help": CircleHelp,
  "clipboard-list": ClipboardList,
  coins: Coins,
  "credit-card": CreditCard,
  download: Download,
  "file-bar-chart": FileBarChart,
  "file-check-2": FileCheck2,
  "file-text": FileText,
  "folder-tree": FolderTree,
  "heart-handshake": HeartHandshake,
  history: History,
  landmark: Landmark,
  "map-pin": MapPin,
  megaphone: Megaphone,
  network: Network,
  package: Package,
  percent: Percent,
  pill: Pill,
  "receipt-text": ReceiptText,
  ruler: Ruler,
  scale: Scale,
  "shield-check": ShieldCheck,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  tags: Tags,
  thermometer: Thermometer,
  "trending-up": TrendingUp,
  truck: Truck,
  "user-round-cog": UserRoundCog,
  "users-round": UsersRound,
  "wallet-cards": WalletCards,
  warehouse: Warehouse,
  "wifi-off": WifiOff,
};

export function YuriIcon({ name, size = 22 }: { name: string; size?: number }) {
  const Icon = iconMap[name] ?? Boxes;
  return <Icon aria-hidden="true" size={size} strokeWidth={1.8} />;
}
